--  Configuration for light_tasking_neorv32 generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Light_Tasking_Neorv32_Config is
   pragma Pure;

   Crate_Version : constant String := "1.0.0-dev";
   Crate_Name : constant String := "light_tasking_neorv32";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "ubuntu";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

   Interrupt_Stack_Size_First : constant :=  256;
   Interrupt_Stack_Size_Last : constant :=  9223372036854775807;
   Interrupt_Stack_Size : constant :=  4096;

   UART0_Baud_Rate_First : constant :=  300;
   UART0_Baud_Rate_Last : constant :=  10000000;
   UART0_Baud_Rate : constant :=  19200;

   Main_Stack_Size_First : constant :=  1024;
   Main_Stack_Size_Last : constant :=  9223372036854775807;
   Main_Stack_Size : constant :=  8192;

   DMEM_Size_First : constant :=  4096;
   DMEM_Size_Last : constant :=  1073741824;
   DMEM_Size : constant :=  65536;

   Clock_Frequency_First : constant :=  1;
   Clock_Frequency_Last : constant :=  1000000000;
   Clock_Frequency : constant :=  50000000;

   IMEM_Size_First : constant :=  4096;
   IMEM_Size_Last : constant :=  1073741824;
   IMEM_Size : constant :=  131072;

end Light_Tasking_Neorv32_Config;
